name: build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++

      - name: Install GTest
        run: |
          cd ~
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=ON
          cmake --build build
          sudo cmake --install build

      - name: Configure and Build with CMake
        run: |
          set -e
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run Tests
        run: |
          set -e
          cd build
          ctest
